const assert = require('assert');
const fs = require('fs');
const path = require('path');
const view = fs.readFileSync(path.join(__dirname, '..', 'views', 'dashboard.ejs'), 'utf8');
const routes = fs.readFileSync(path.join(__dirname, '..', 'routes', 'generations.js'), 'utf8');
assert(!view.includes('<%- error %>'));
assert(view.includes('<%= error %>'));
assert(view.includes('<%= errorAction.href %>'));
assert(!routes.includes('Monthly generation limit reached. <a'));
assert(!/console\.(?:warn|error)\([^\n]*(?:err|e|e2)\.(?:message|stack)/.test(routes));
assert.match(routes, /event: 'dashboard_data_failed'/);
assert.match(routes, /code: 'DASHBOARD_DATA_FAILED'/);
assert.match(routes, /event: 'dashboard_render_failed'/);
assert.match(routes, /errorAction: \{ href: '\/pricing'/);
assert(!view.includes('listEl.innerHTML=sec.deliverables'));
assert(!view.includes('platformsEl.innerHTML = chips'));
assert(!view.includes('groupsEl.innerHTML = h'));
assert.doesNotMatch(view, /bjBlueprintPanel|renderBlueprint|bpGroups/);
assert.doesNotMatch(view, /campaignSections|campaign-sec-btn|mode-campaign/);
console.log('Story 3.40 dashboard rendering safety tests passed');
