const MINIMUM_PRODUCTION_DEPENDENCIES = Object.freeze({
  acquisition_snapshot: Object.freeze([]),
  acquisition_channel_strategy: Object.freeze(['acquisition_snapshot']),
  campaign_brief: Object.freeze(['acquisition_snapshot', 'acquisition_channel_strategy']),
  conversion_path_brief: Object.freeze(['acquisition_snapshot', 'campaign_brief']),
  outreach_sequence: Object.freeze(['campaign_brief', 'conversion_path_brief']),
  referral_campaign_kit: Object.freeze(['campaign_brief', 'conversion_path_brief']),
  paid_ad_copy_set: Object.freeze(['campaign_brief', 'conversion_path_brief']),
  social_lead_campaign: Object.freeze(['campaign_brief', 'conversion_path_brief']),
  organic_content_campaign: Object.freeze(['campaign_brief', 'conversion_path_brief']),
  lead_capture_page: Object.freeze(['campaign_brief', 'conversion_path_brief']),
  sales_call_script: Object.freeze(['campaign_brief', 'conversion_path_brief']),
  multi_channel_campaign_kit: Object.freeze(['campaign_brief', 'conversion_path_brief']),
  acquisition_measurement_plan: Object.freeze(['acquisition_channel_strategy', 'conversion_path_brief']),
  acquisition_experiment_backlog: Object.freeze(['acquisition_measurement_plan']),
  conversion_diagnostic_brief: Object.freeze([]),
  consultation_conversion_brief: Object.freeze(['conversion_diagnostic_brief']),
  consultation_conversion_page_copy: Object.freeze(['consultation_conversion_brief']),
  conversion_page_brief: Object.freeze(['conversion_diagnostic_brief']),
  conversion_measurement_plan: Object.freeze(['conversion_diagnostic_brief']),
  search_evidence_snapshot: Object.freeze([]),
  search_strategy: Object.freeze(['search_evidence_snapshot']),
  priority_content_brief: Object.freeze(['search_evidence_snapshot', 'search_strategy']),
  research_evidence_pack: Object.freeze(['priority_content_brief']),
  priority_search_article: Object.freeze(['priority_content_brief', 'research_evidence_pack']),
  search_measurement_plan: Object.freeze(['search_strategy']),
  customer_profile: Object.freeze([]),
  product_concept_brief: Object.freeze(['customer_profile']),
  product_specification_brief: Object.freeze(['product_concept_brief']),
  product_positioning: Object.freeze(['customer_profile']),
  value_proposition: Object.freeze(['customer_profile', 'product_positioning']),
  validation_plan: Object.freeze(['customer_profile', 'product_concept_brief', 'product_positioning', 'value_proposition']),
  prototype_sample_validation_plan: Object.freeze(['product_specification_brief', 'validation_plan']),
  sourcing_manufacturer_brief: Object.freeze(['product_specification_brief']),
  compliance_evidence_checklist: Object.freeze(['product_specification_brief']),
  unit_economics_pricing_model: Object.freeze(['product_specification_brief', 'sourcing_manufacturer_brief']),
  packaging_shipping_requirements: Object.freeze(['product_specification_brief', 'compliance_evidence_checklist']),
  inventory_fulfillment_plan: Object.freeze(['sourcing_manufacturer_brief', 'unit_economics_pricing_model', 'packaging_shipping_requirements']),
  core_messaging: Object.freeze(['customer_profile', 'product_positioning', 'value_proposition']),
  amazon_listing: Object.freeze(['product_positioning', 'core_messaging']),
  amazon_bullet_points: Object.freeze(['amazon_listing']),
  amazon_keyword_guidance: Object.freeze([]),
  amazon_a_plus: Object.freeze(['amazon_listing', 'core_messaging']),
  ecommerce_product_page: Object.freeze(['product_positioning', 'core_messaging']),
  ecommerce_trust_faq: Object.freeze(['ecommerce_product_page']),
  ecommerce_conversion_copy: Object.freeze(['ecommerce_product_page']),
  abandoned_cart_email: Object.freeze(['ecommerce_product_page', 'core_messaging']),
  google_business_profile: Object.freeze(['core_messaging']),
  service_page: Object.freeze(['product_positioning', 'core_messaging']),
  product_image_guidance: Object.freeze(['product_positioning']),
  software_product_demo: Object.freeze(['core_messaging']),
  saas_trial_emails: Object.freeze(['software_product_demo', 'core_messaging']),
  launch_announcement: Object.freeze(['core_messaging']),
  educational_content: Object.freeze(['core_messaging']),
  social_launch_campaign: Object.freeze(['core_messaging', 'launch_announcement'])
});

function minimumProductionDependencies(deliverableId) {
  return [...(MINIMUM_PRODUCTION_DEPENDENCIES[deliverableId] || [])];
}

module.exports = { MINIMUM_PRODUCTION_DEPENDENCIES, minimumProductionDependencies };
