const HARD_LIMITS = Object.freeze({
  need: Object.freeze({ discoveryAttempts: 2, webSearchActions: 1, reconciliationCalls: 5, entailmentCalls: 3, costUsd: 0.05, elapsedMs: 90000 }),
  pack: Object.freeze({ researchNeeds: 5, webSearchActions: 5, extractionSources: 3, parserCalls: 3, externalCalls: 20, costUsd: 0.15, elapsedMs: 150000 })
});
const RESERVATIONS = Object.freeze({ web_search: 0.025, source_extraction: 0.001, proposition_parsing: 0.003, source_reconciliation: 0.001, entailment: 0.001 });
const LABELS = Object.freeze({ NOT_REQUIRED: 'No research needed', QUEUED: 'Researching', RUNNING_DISCOVERY: 'Researching', RUNNING_EXTRACTION: 'Researching', RUNNING_VALIDATION: 'Researching', SUPPORTED: 'Research complete', PARTIAL: 'Research complete with limitations', INSUFFICIENT: 'More evidence needed', PROVIDER_UNAVAILABLE: 'Research temporarily unavailable', BUDGET_EXHAUSTED: 'Research temporarily unavailable', CANCELLED: 'Research stopped', BLOCKED: 'Blocked pending evidence' });
const clean = value => String(value || '').trim();
const money = value => Number(Math.max(0, Number(value) || 0).toFixed(8));
const bounded = (value, fallback, maximum) => { const parsed = Number(value); return Number.isFinite(parsed) && parsed > 0 ? Math.min(parsed, maximum) : fallback; };
function researchOperationsPolicy(env = process.env) { return Object.freeze({ needCostUsd: bounded(env.RESEARCH_NEED_COST_LIMIT_USD, HARD_LIMITS.need.costUsd, HARD_LIMITS.need.costUsd), needElapsedMs: bounded(env.RESEARCH_NEED_TIMEOUT_MS, HARD_LIMITS.need.elapsedMs, HARD_LIMITS.need.elapsedMs), packCostUsd: bounded(env.RESEARCH_PACK_COST_LIMIT_USD, HARD_LIMITS.pack.costUsd, HARD_LIMITS.pack.costUsd), packElapsedMs: bounded(env.RESEARCH_PACK_TIMEOUT_MS, HARD_LIMITS.pack.elapsedMs, HARD_LIMITS.pack.elapsedMs), externalCalls: Math.floor(bounded(env.RESEARCH_PACK_MAX_EXTERNAL_CALLS, HARD_LIMITS.pack.externalCalls, HARD_LIMITS.pack.externalCalls)) }); }
function operationalCategory(code) { const value = clean(code).toUpperCase(); if (/AUTHORIZATION/.test(value)) return 'AUTHORIZATION_FAILURE'; if (/BILLING/.test(value)) return 'BILLING_FAILURE'; if (/RATE_LIMIT/.test(value)) return 'RATE_LIMITED'; if (/TIMEOUT|DEADLINE/.test(value)) return 'TIMEOUT'; if (/LEASE|CLAIM_OWNERSHIP/.test(value)) return 'LEASE_LOSS'; if (/CANCEL/.test(value)) return 'CANCELLED'; if (/BUDGET/.test(value)) return 'BUDGET_EXHAUSTED'; if (/AMBIGUOUS/.test(value)) return 'AMBIGUOUS_COMPLETION'; if (/PARSER/.test(value)) return 'PARSER_FAILURE'; if (/EXTRACTION|SOURCE_UNAVAILABLE|DNS|CONNECTION|TLS/.test(value)) return 'EXTRACTION_FAILURE'; if (/INSUFFICIENT|UNSUPPORTED|STALE|WEAK|CONFLICT/.test(value)) return 'EVIDENCE_INSUFFICIENT'; if (/RESEARCH_PROVIDER|DISCOVERY|NO_SEARCH|SOURCES_MISSING/.test(value)) return 'DISCOVERY_FAILURE'; return 'INTERNAL_FAILURE'; }
function budgetError(code) { return Object.assign(new Error('Research operations budget prevented a provider call.'), { code, operationalCategory: operationalCategory(code) }); }
function createResearchOperations({ env = process.env, now = () => Date.now() } = {}) {
  const policy = researchOperationsPolicy(env), started = now(), deadline = started + policy.packElapsedMs, needs = new Map(), active = new Map(), counts = {}, failures = [], versions = new Set(), extractionSources = new Set(); let next = 1, calls = 0, cost = 0, reported = 0, unknown = 0, providerMs = 0, inputTokens = 0, outputTokens = 0;
  const need = (key, essential = false) => { key = clean(key) || 'unknown'; if (!needs.has(key)) needs.set(key, { key, essential, started: now(), completed: null, status: 'QUEUED', counts: {}, cost: 0, providerMs: 0, considered: 0, retrieved: 0, accepted: 0, failure: '' }); return needs.get(key); };
  function reserve(action, options = {}) { const current = now(), item = need(options.needKey, options.essential), estimate = money(options.estimatedCostUsd ?? RESERVATIONS[action] ?? 0); if (current >= deadline || current - item.started >= policy.needElapsedMs) throw budgetError('RESEARCH_DEADLINE_EXCEEDED'); if (calls >= policy.externalCalls || cost + estimate > policy.packCostUsd || item.cost + estimate > policy.needCostUsd) throw budgetError('RESEARCH_PROVIDER_BUDGET_EXHAUSTED'); const used = item.counts[action] || 0, extractionKey = clean(options.sourceKey); if (action === 'web_search' && used >= HARD_LIMITS.need.discoveryAttempts || action === 'source_reconciliation' && used >= 5 || action === 'entailment' && used >= 3 || action === 'source_extraction' && extractionKey && !extractionSources.has(extractionKey) && extractionSources.size >= 3 || action === 'proposition_parsing' && (counts[action] || 0) >= 3) throw budgetError('RESEARCH_PROVIDER_BUDGET_EXHAUSTED'); if (action === 'source_extraction' && extractionKey) extractionSources.add(extractionKey); const id = next++; active.set(id, { id, action, key: item.key, estimate, started: current }); calls++; cost = money(cost + estimate); item.cost = money(item.cost + estimate); counts[action] = (counts[action] || 0) + 1; item.counts[action] = used + 1; item.status = action === 'web_search' ? 'RUNNING_DISCOVERY' : action === 'source_extraction' ? 'RUNNING_EXTRACTION' : 'RUNNING_VALIDATION'; return Object.freeze({ id, remainingTimeMs: Math.max(1, Math.min(deadline - current, policy.needElapsedMs - (current - item.started))) }); }
  function reconcile(token, metadata = {}) { const reservation = active.get(token?.id); if (!reservation) return false; active.delete(token.id); const item = need(reservation.key), duration = Math.max(0, Number(metadata.durationMs) || now() - reservation.started); providerMs += duration; item.providerMs += duration; const providerCost = Number(metadata.providerReportedCostUsd), estimate = Number(metadata.estimatedCostUsd), actual = Number.isFinite(providerCost) && providerCost >= 0 ? providerCost : Number.isFinite(estimate) && estimate >= 0 ? estimate : null; if (actual === null) unknown++; else { const delta = Number((actual - reservation.estimate).toFixed(8)); cost = money(cost + delta); item.cost = money(item.cost + delta); } if (Number.isFinite(providerCost) && providerCost >= 0) reported = money(reported + providerCost); inputTokens += Math.max(0, Number(metadata.inputTokens) || 0); outputTokens += Math.max(0, Number(metadata.outputTokens) || 0); if (metadata.pricingVersion) versions.add(clean(metadata.pricingVersion)); if (metadata.failureCode) { item.failure = operationalCategory(metadata.failureCode); failures.push({ providerCategory: clean(metadata.providerCategory).slice(0, 40), operationCategory: reservation.action, failureCategory: item.failure, code: clean(metadata.failureCode).slice(0, 80) }); } return true; }
  function completeNeed(key, details = {}) { const item = need(key, details.essential); item.completed = now(); item.status = details.status || item.status; item.considered = Number(details.sourcesConsidered) || 0; item.retrieved = Number(details.sourcesRetrieved) || 0; item.accepted = Number(details.evidenceAccepted) || 0; if (details.failureCategory) item.failure = details.failureCategory; }
  function summary(status, aggregate = {}) { const completed = now(), durationMs = Math.max(0, completed - started), needOperations = [...needs.values()].slice(0, 5).map(item => ({ needKey: item.key, essential: item.essential, status: item.status, discoveryAttempts: item.counts.web_search || 0, sourcesConsidered: item.considered, sourcesRetrieved: item.retrieved, evidenceAccepted: item.accepted, durationMs: Math.max(0, (item.completed || completed) - item.started), estimatedCostUsd: money(item.cost), failureCategory: item.failure })); return Object.freeze({ status, startedAt: new Date(started).toISOString(), completedAt: new Date(completed).toISOString(), durationMs, providerDurationMs: providerMs, processingDurationMs: Math.max(0, durationMs - providerMs), researchNeedCount: aggregate.researchNeedCount ?? needOperations.length, supportedNeedCount: aggregate.supportedNeedCount || 0, insufficientNeedCount: aggregate.insufficientNeedCount || 0, blockedNeedCount: aggregate.blockedNeedCount || 0, discoveryAttempts: counts.web_search || 0, webSearchActions: aggregate.webSearchActions || 0, nativeSourceCount: aggregate.nativeSourceCount || 0, eligibleSourceCount: aggregate.eligibleSourceCount || 0, extractionAttempts: counts.source_extraction || 0, retrievedSourceCount: aggregate.retrievedSourceCount || 0, parserCalls: counts.proposition_parsing || 0, reconciliationCalls: counts.source_reconciliation || 0, entailmentCalls: counts.entailment || 0, inputTokens, outputTokens, estimatedCostUsd: money(cost), providerReportedCostUsd: money(reported), unknownCostOperationCount: unknown, pricingVersions: [...versions], providerFailures: failures.slice(0, 20), budgetState: { externalCallsUsed: calls, externalCallsLimit: policy.externalCalls, estimatedCostUsd: money(cost), estimatedCostLimitUsd: policy.packCostUsd, elapsedMs: durationMs, elapsedLimitMs: policy.packElapsedMs, exhausted: status === 'BUDGET_EXHAUSTED' }, needOperations }); }
  return Object.freeze({ policy, deadline, need, reserve, reconcile, completeNeed, summary, remainingTimeMs: () => Math.max(0, deadline - now()) });
}
function customerResearchStatus(status) { return LABELS[status] || LABELS.INSUFFICIENT; }
function createProviderBreaker(provider, { now = () => Date.now(), threshold = 3, windowMs = 300000, cooldownMs = 60000 } = {}) { let state = 'CLOSED', failures = [], openedAt = 0, permanent = false, probing = false; return Object.freeze({ provider, allow() { const current = now(); if (state === 'OPEN' && !permanent && current - openedAt >= cooldownMs) { state = 'HALF_OPEN'; probing = false; } if (state === 'OPEN' || state === 'HALF_OPEN' && probing) return false; if (state === 'HALF_OPEN') probing = true; return true; }, success() { state = 'CLOSED'; failures = []; permanent = false; probing = false; }, failure(code) { const type = operationalCategory(code); if (['AUTHORIZATION_FAILURE', 'BILLING_FAILURE'].includes(type)) { state = 'OPEN'; permanent = true; openedAt = now(); return; } if (!['DISCOVERY_FAILURE', 'EXTRACTION_FAILURE', 'RATE_LIMITED', 'TIMEOUT', 'PARSER_FAILURE'].includes(type)) return; const current = now(); failures = failures.filter(value => current - value <= windowMs); failures.push(current); if (state === 'HALF_OPEN' || failures.length >= threshold) { state = 'OPEN'; openedAt = current; probing = false; } }, snapshot: () => ({ provider, state, consecutiveTransientFailures: failures.length, permanent }) }); }
const breakers = new Map(); function providerBreaker(provider, options) { if (!breakers.has(provider)) breakers.set(provider, createProviderBreaker(provider, options)); return breakers.get(provider); } function resetProviderBreakers() { breakers.clear(); }
module.exports = { HARD_LIMITS, LABELS, RESERVATIONS, createProviderBreaker, createResearchOperations, customerResearchStatus, operationalCategory, providerBreaker, researchOperationsPolicy, resetProviderBreakers };
